### ISSUE TITLE
Error occurred when I use Custom Entry to retarget from Plask AI Mocap to Rigify rig.

### ISSUE THREAD

**Issue by kuyum** [Rokoko/rokoko-studio-live-blender#104]
I followed this turorial to do my retargeting [https://www.youtube.com/watch?v=5nHgYO8vzf4](https://www.youtube.com/watch?v=5nHgYO8vzf4). But my source motion is from Plask AI Mocap. When no custom entry, the retargeting is fine. For the purpose that one source bone to control different target bone, I add custom entry, then the error occurred.
Error:
Python: Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\rokoko-studio-live-blender-master\operators\detector.py", line 108, in execute
    custom_schemes_manager.save_retargeting_to_list()
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\rokoko-studio-live-blender-master\core\custom_schemes_manager.py", line 54, in save_retargeting_to_list
    if bone_name_target not in detection_manager.bone_detection_list_custom[bone_name_key_detected]:
KeyError: 'custom_bone_leftupleg'
-----------------
My OS：Windows 10
Blender: Blender 3.3
rokoko-studio-live-blender: 1.4.0
--------------
My custom entry:
leftArm  >  upper_arm_ik.L
leftHand  >  hand_ik.L
leftToeBase  >  toe_ik.L
leftFoot  >  foot_ik.L
leftUpLeg  >  thigh_ik.L
rightArm  >  upper_arm_ik.R
rightHand  >  hand_ik.R
rightToeBase  >  toe_ik.R
rightFoot  >  foot_ik.R
rightUpLeg  >  thigh_ik.R
---------------
additional:
When I added these custom entries, the Save operator has an error too. When I added a few of these items, it had no error reported. But the json file didn't have these entries,  so the Import and Rebuild Bone List didn't have these custom entries.
When there is no custom entries, it works, but there is something I am curiors. I check the exported scheme json file, there is an entry         "rightUpLeg": ["shin_fk.r"], but the strange thing is that in my settings is "rightUpLeg": ["thigh_fk.r"].

**Comment by calvininvictus** [comment]
I am having a similar issue when adding a custom entry. Did you find a work around?
Of all the videos ive seen, adding custom entries seems to work with IK bones.
