### ISSUE TITLE
An issue while attempting to uninstall

### ISSUE THREAD

**Issue by EverythingerTruten** [Rokoko/rokoko-studio-live-blender#107]
Hello, I need to uninstall rokoko studio from blender, but when I try to click it, this error message shows up:

`Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\startup\bl_operators\userpref.py", line 764, in execute
    shutil.rmtree(path)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\shutil.py", line 739, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\shutil.py", line 612, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\shutil.py", line 612, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\shutil.py", line 612, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  [Previous line repeated 3 more times]
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\shutil.py", line 617, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\shutil.py", line 615, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Odmowa dostępu` **[I'VE GOT BLENDER IN POLISH. THIS MEANS ACCESS DENIED]** `: 'C:\\Users\\`**[ MY USERNAME]**`\\AppData\\Roaming\\Blender Foundation\\Blender\\3.3\\scripts\\addons\\rokoko-studio-live-blender-master\\resources\\libraries\\python310\\cryptography\\hazmat\\bindings\\_rust.pyd'`

What's happening here, and how can I fix this?

**Comment by Darkblader24** [comment]
Thank you, this issue is fixed in the latest beta version.
