### ISSUE TITLE
no module named boto3 - update for blender 3.5 pls

### ISSUE THREAD

**Issue by jurassicjordan** [Rokoko/rokoko-studio-live-blender#109]
this error occurs in blender 3.5

Traceback (most recent call last):
  File "/home/jordancruz/Tools/Blender-Versions/Blender/3.5/scripts/modules/addon_utils.py", line 421, in disable
    mod.unregister()
  File "/home/jordancruz/.config/blender/3.5/scripts/addons/rokoko-studio-live-blender-1-4-1/__init__.py", line 361, in unregister
    from . import operators
  File "/home/jordancruz/.config/blender/3.5/scripts/addons/rokoko-studio-live-blender-1-4-1/operators/__init__.py", line 3, in <module>
    from . import receiver
  File "/home/jordancruz/.config/blender/3.5/scripts/addons/rokoko-studio-live-blender-1-4-1/operators/receiver.py", line 5, in <module>
    from ..core import state_manager
  File "/home/jordancruz/.config/blender/3.5/scripts/addons/rokoko-studio-live-blender-1-4-1/core/__init__.py", line 14, in <module>
    from . import login_manager
  File "/home/jordancruz/.config/blender/3.5/scripts/addons/rokoko-studio-live-blender-1-4-1/core/login_manager.py", line 7, in <module>
    import boto3
ModuleNotFoundError: No module named 'boto3'

**Comment by Darkblader24** [comment]
Hey, please try the beta version, you can use the built-in updater or use this link: https://github.com/Rokoko/rokoko-studio-live-blender/archive/refs/heads/beta.zip

**Comment by jurassicjordan** [comment]
Thank you so much, beta is working way better. Can't wait for next release.
