### ISSUE TITLE
Doesn't work on Linux

### ISSUE THREAD

**Issue by Hard3D** [Rokoko/rokoko-studio-live-blender#46]
Not sure you made it cross platform or not, but your addon pretty interesting and very wanted on free OS :)

**Error**

```
Traceback (most recent call last):
  File "/snap/blender/41/2.83/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/viadvena/.config/blender/2.83/scripts/addons/rokoko-studio-live-blender-beta/__init__.py", line 22, in <module>
    from . import core
  File "/home/viadvena/.config/blender/2.83/scripts/addons/rokoko-studio-live-blender-beta/core/__init__.py", line 7, in <module>
    from . import state_manager
  File "/home/viadvena/.config/blender/2.83/scripts/addons/rokoko-studio-live-blender-beta/core/state_manager.py", line 4, in <module>
    from ..operators import receiver
  File "/home/viadvena/.config/blender/2.83/scripts/addons/rokoko-studio-live-blender-beta/operators/__init__.py", line 10, in <module>
    from . import login
  File "/home/viadvena/.config/blender/2.83/scripts/addons/rokoko-studio-live-blender-beta/operators/login.py", line 3, in <module>
    from ..core import login
  File "/home/viadvena/.config/blender/2.83/scripts/addons/rokoko-studio-live-blender-beta/core/login.py", line 5, in <module>
    from ctypes import wintypes
  File "/snap/blender/41/2.83/python/lib/python3.7/ctypes/wintypes.py", line 20, in <module>
    class VARIANT_BOOL(ctypes._SimpleCData):
ValueError: _type_ 'v' not supported
```

My platform

**System Information**
Operating system: Linux-4.15.0-111-generic-x86_64-with-debian-buster-sid 64 Bits  (Ubuntu 18.04)
Graphics card: GeForce GTX 1050 Ti/PCIe/SSE2 NVIDIA Corporation 4.5.0 NVIDIA 435.21

**Blender Version**
Broken: version: 2.83.2, branch: master, commit date: 2020-07-09 05:50, hash: `rB239fbf7d936f`
Worked: (newest version of Blender that worked as expected)

**Comment by Darkblader24** [comment]
Support for Mac and Linux will be added in the full update. It will be released very soon.

**Comment by Darkblader24** [comment]
The update is released, it should work now on Linux
