### ISSUE TITLE
Plugin error when retargeting in Blender 2.92

### ISSUE THREAD

**Issue by David-Lindberg-Rokoko** [Rokoko/rokoko-studio-live-blender#65]
A customer has reported an error message when attempting to retarget. "Only a few keys get transferred, then the following error message occurs":

Python: Traceback (most recent call last):
  File "C:\Users\Zuluan\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\rokoko-studio-live-blender-master\operators\retargeting.py", line 195, in execute
    self.bake_animation(armature_source, armature_target, root_bones)
  File "C:\Users\Zuluan\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\rokoko-studio-live-blender-master\operators\retargeting.py", line 433, in bake_animation
    bpy.ops.nla.bake(frame_start=start, frame_end=end, visual_keying=True, only_selected=True, use_current_action=False, bake_types={'POSE'})
  File "Z:\Program Files\Blender 2.92\2.92\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "Z:\Program Files\Blender 2.92\2.92\scripts\startup\bl_operators\anim.py", line 290, in execute
    do_clean=self.clean_curves,
  File "Z:\Program Files\Blender 2.92\2.92\scripts\modules\bpy_extras\anim_utils.py", line 80, in bake_action_objects
    return iter.send(None)
  File "Z:\Program Files\Blender 2.92\2.92\scripts\modules\bpy_extras\anim_utils.py", line 111, in bake_action_objects_iter
    yield tuple(iter.send(None) for iter in iter_all)
  File "Z:\Program Files\Blender 2.92\2.92\scripts\modules\bpy_extras\anim_utils.py", line 111, in <genexpr>
    yield tuple(iter.send(None) for iter in iter_all)
  File "Z:\Program Files\Blender 2.92\2.92\scripts\modules\bpy_extras\anim_utils.py", line 299, in bake_action_iter
    euler = pbone.matrix_basis.to_euler(obj.rotation_mode, euler_prev)
ValueError: Matrix.to_euler(): invalid euler order 'QUATERNION'
 
location: Z:\Program Files\Blender 2.92\2.92\scripts\modules\bpy\ops.py:132
 
 
 
location: <unknown location>:-1

**Comment by delgelato** [comment]
Hi i'm also getting this, also on 2.92
Will this be fixed?

**Comment by Respect679** [comment]
Python: Traceback (most recent call last):
  File "C:\Users\su190\AppData\Roaming\Blender Foundation\Blender\5.0\scripts\addons\rokoko-studio-live-blender-master\operators\retargeting.py", line 34, in execute
    retargeting_dict = detector.detect_retarget_bones()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\su190\AppData\Roaming\Blender Foundation\Blender\5.0\scripts\addons\rokoko-studio-live-blender-master\core\detection_manager.py", line 298, in detect_retarget_bones
    for fc in armature_source.animation_data.action.fcurves:
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Action' object has no attribute 'fcurves'
 plz help i keep getting this error
