### ISSUE TITLE
Unable to log into plugin

### ISSUE THREAD

**Issue by andrewbrianis** [Rokoko/rokoko-studio-live-blender#66]
Hello, trying to get the plugin setup on a new Windows 10 20h2 laptop running blender 2.92. The plugin installs, but then I get an error message when trying to log into the plugin.

Python: Traceback (most recent call last):
  File "C:\Users\Andrew Brian\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\rokoko-studio-live-blender-1-2-1\operators\login.py", line 17, in execute
    if login.login(context.scene.rsl_login_email, password):
  File "C:\Users\Andrew Brian\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\rokoko-studio-live-blender-1-2-1\core\login.py", line 127, in login
    load()
  File "C:\Users\Andrew Brian\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\rokoko-studio-live-blender-1-2-1\core\login.py", line 70, in load
    lib = ctypes.CDLL(lib_file)
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\python\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

location: <unknown location>:-1

**Comment by David-Lindberg-Rokoko** [comment]
A customer fixed the issue on their own PC, by installing the following package: https://support.microsoft.com/en-us/topic/update-for-visual-c-2013-redistributable-package-d8ccd6a5-4e26-c290-517b-8da6cfdf4f10
