### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by jacobcosquer** [Rokoko/rokoko-studio-live-blender#85]
When trying to sign into the plugin within Blender, I get the following error;

Python: Traceback (most recent call last):
  File "/Users/jacobcosquer/Library/Application Support/Blender/3.1/scripts/addons/rokoko-studio-live-blender-master/operators/login.py", line 18, in execute
    if login.login(context.scene.rsl_login_email, password):
  File "/Users/jacobcosquer/Library/Application Support/Blender/3.1/scripts/addons/rokoko-studio-live-blender-master/core/login.py", line 164, in login
    if not load():
  File "/Users/jacobcosquer/Library/Application Support/Blender/3.1/scripts/addons/rokoko-studio-live-blender-master/core/login.py", line 98, in load
    lib = ctypes.CDLL(lib_file.replace("\\", "/"))
  File "/Applications/Blender.app/Contents/Resources/3.1/python/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/jacobcosquer/Library/Application Support/Blender/3.1/scripts/addons/rokoko-studio-live-blender-master/resources/libs/mac/librokoko-id.dylib, 0x0006): tried: '/Users/jacobcosquer/Library/Application Support/Blender/3.1/scripts/addons/rokoko-studio-live-blender-master/resources/libs/mac/librokoko-id.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/librokoko-id.dylib' (no such file)

location: <unknown location>:-1

Please help! Currently running on an M1 Mac, Latest Blender Release.

**Comment by Darkblader24** [comment]
Hey, we are working on a new version, could you please give it a try and let me know if it worked? https://github.com/Rokoko/rokoko-studio-live-blender/archive/refs/heads/login_rework.zip

**Comment by Darkblader24** [comment]
Hey, we fixed this issue. Please try again using this version here: https://github.com/Rokoko/rokoko-studio-live-blender/archive/refs/heads/beta.zip
